import turtle
turtle.shape("turtle")

turtle.pencolor("red")
turtle.pensize(3)
turtle.forward(35)
turtle.left(90)
turtle.forward(100)
turtle.right(90)
turtle.forward(30)
turtle.right(90)
turtle.forward(100)
turtle.left(90)
turtle.forward(20)
turtle.left(90)
turtle.forward(100)
turtle.right(90)
turtle.forward(60)
turtle.right(90)
turtle.forward(100)
turtle.left(90)
turtle.forward(20)

turtle.done()
